"""Generate the floating-ball MJCF assets from the canonical model."""

from __future__ import annotations

import argparse
import difflib
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ASSET_DIR = Path(__file__).resolve().parent
SOURCE_MODEL = ASSET_DIR / "asRoBallet.xml"
SOURCE_SCENE = ASSET_DIR / "scene.xml"
FLOATING_MODEL = ASSET_DIR / "asRoBallet_floating_ball.xml"
FLOATING_SCENE = ASSET_DIR / "scene_floating_ball.xml"
GENERATED_NOTICE = "<!-- Generated by generate_variants.py; do not edit directly. -->\n"
FLOATING_BALL_POSITION = "-0.000184 0.0 0.1138"


def _required(parent: ET.Element | None, path: str) -> ET.Element:
    """Return a required child element or fail with a useful error."""
    if parent is None:
        raise ValueError(f"Missing required MJCF element: {path}")
    element = parent.find(path)
    if element is None:
        raise ValueError(f"Missing required MJCF element: {path}")
    return element


def _serialize(tree: ET.ElementTree) -> str:
    """Serialize a generated XML tree with stable formatting."""
    ET.indent(tree, space="  ")
    return GENERATED_NOTICE + ET.tostring(tree.getroot(), encoding="unicode") + "\n"


def _generate_floating_model() -> str:
    tree = ET.parse(SOURCE_MODEL)
    root = tree.getroot()
    worldbody = _required(root, "worldbody")
    base_link = _required(worldbody, "./body[@name='base_link']")
    ball_link = _required(base_link, "./body[@name='ball_link']")
    ball_joint = _required(ball_link, "./joint[@name='torso_ball_joint']")

    if ball_joint.get("type") != "ball":
        raise ValueError("torso_ball_joint must be a ball joint in the canonical model")

    joint_index = list(ball_link).index(ball_joint)
    ball_link.remove(ball_joint)
    ball_link.insert(joint_index, ET.Element("freejoint", {"name": "ball_free_joint"}))
    ball_link.set("pos", FLOATING_BALL_POSITION)

    base_link.remove(ball_link)
    worldbody.append(ball_link)
    return _serialize(tree)


def _generate_floating_scene() -> str:
    tree = ET.parse(SOURCE_SCENE)
    include = _required(tree.getroot(), "./include[@file='asRoBallet.xml']")
    include.set("file", FLOATING_MODEL.name)
    return _serialize(tree)


def _update(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == content:
        return True

    if check:
        diff = difflib.unified_diff(
            current.splitlines(),
            content.splitlines(),
            fromfile=str(path),
            tofile=f"generated {path}",
            lineterm="",
        )
        print("\n".join(diff), file=sys.stderr)
        return False

    path.write_text(content, encoding="utf-8")
    print(f"Generated {path.relative_to(ASSET_DIR.parent.parent)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that checked-in variants match the canonical MJCF assets",
    )
    args = parser.parse_args()

    outputs = (
        (FLOATING_MODEL, _generate_floating_model()),
        (FLOATING_SCENE, _generate_floating_scene()),
    )
    results = [_update(path, content, args.check) for path, content in outputs]
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
